name: Update stars badges in README

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-stars:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update README
        run: cog -r README.md
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
          AOC_UID: ${{ secrets.AOC_UID }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update stars count"
          file_pattern: README.md
